# Generated by Django 5.0.6 on 2024-10-25 18:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MultimodalOrchestrationChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization_name', models.CharField(blank=True, max_length=10000, null=True)),
                ('agent_name', models.CharField(blank=True, max_length=10000, null=True)),
                ('chat_name', models.CharField(blank=True, max_length=10000, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Multimodal Orchestration Chat',
                'verbose_name_plural': 'Multimodal Orchestration Chats',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AssistantConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('connection_endpoint', models.CharField(blank=True, max_length=10000, null=True)),
                ('connection_is_public', models.BooleanField(default=False)),
                ('connection_api_key', models.CharField(blank=True, max_length=10000, null=True)),
                ('connection_agent_name', models.CharField(blank=True, max_length=10000, null=True)),
                ('connection_agent_description', models.CharField(blank=True, max_length=10000, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Assistant Connection',
                'verbose_name_plural': 'Assistant Connections',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['created_at'], name='messaging_a_created_8d6ce4_idx')],
            },
        ),
        migrations.CreateModel(
            name='LeanmodConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('connection_endpoint', models.CharField(blank=True, max_length=10000, null=True)),
                ('connection_is_public', models.BooleanField(default=False)),
                ('connection_api_key', models.CharField(blank=True, max_length=10000, null=True)),
                ('connection_agent_name', models.CharField(blank=True, max_length=10000, null=True)),
                ('connection_agent_description', models.CharField(blank=True, max_length=10000, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'LeanMod Connection',
                'verbose_name_plural': 'LeanMod Connections',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['created_at'], name='messaging_l_created_ed1276_idx')],
            },
        ),
        migrations.CreateModel(
            name='MultimodalAssistantChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization_name', models.CharField(blank=True, max_length=10000, null=True)),
                ('agent_name', models.CharField(blank=True, max_length=10000, null=True)),
                ('chat_name', models.CharField(blank=True, max_length=10000, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('connection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='multimodal_assistant_chats', to='messaging.assistantconnection')),
            ],
            options={
                'verbose_name': 'Multimodal Assistant Chat',
                'verbose_name_plural': 'Multimodal Assistant Chats',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MultimodalAssistantChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_role', models.CharField(choices=[('system', 'System'), ('assistant', 'Assistant'), ('user', 'User')], default='system', max_length=200)),
                ('message_text', models.TextField(blank=True, null=True)),
                ('message_file_uris', models.JSONField(blank=True, null=True)),
                ('message_image_uris', models.JSONField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assistant_messages', to='messaging.multimodalassistantchat')),
            ],
            options={
                'verbose_name': 'Multimodal Assistant Chat Message',
                'verbose_name_plural': 'Multimodal Assistant Chat Messages',
                'ordering': ['-sent_at'],
            },
        ),
        migrations.CreateModel(
            name='MultimodalLeanmodChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization_name', models.CharField(blank=True, max_length=10000, null=True)),
                ('agent_name', models.CharField(blank=True, max_length=10000, null=True)),
                ('chat_name', models.CharField(blank=True, max_length=10000, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('connection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='multimodal_leanmod_chats', to='messaging.leanmodconnection')),
            ],
            options={
                'verbose_name': 'Multimodal LeanMod Chat',
                'verbose_name_plural': 'Multimodal LeanMod Chats',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MultimodalLeanmodChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_role', models.CharField(choices=[('system', 'System'), ('assistant', 'Assistant'), ('user', 'User')], default='system', max_length=200)),
                ('message_text', models.TextField(blank=True, null=True)),
                ('message_file_uris', models.JSONField(blank=True, null=True)),
                ('message_image_uris', models.JSONField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leanmod_messages', to='messaging.multimodalleanmodchat')),
            ],
            options={
                'verbose_name': 'Multimodal LeanMod Chat Message',
                'verbose_name_plural': 'Multimodal LeanMod Chat Messages',
                'ordering': ['-sent_at'],
            },
        ),
        migrations.CreateModel(
            name='MultimodalOrchestrationChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_role', models.CharField(choices=[('system', 'System'), ('assistant', 'Assistant'), ('user', 'User')], default='system', max_length=200)),
                ('message_text', models.TextField(blank=True, null=True)),
                ('message_file_uris', models.JSONField(blank=True, null=True)),
                ('message_image_uris', models.JSONField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orchestration_messages', to='messaging.multimodalorchestrationchat')),
            ],
            options={
                'verbose_name': 'Multimodal Orchestration Chat Message',
                'verbose_name_plural': 'Multimodal Orchestration Chat Messages',
                'ordering': ['-sent_at'],
            },
        ),
        migrations.CreateModel(
            name='OrchestrationConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('connection_endpoint', models.CharField(blank=True, max_length=10000, null=True)),
                ('connection_is_public', models.BooleanField(default=False)),
                ('connection_api_key', models.CharField(blank=True, max_length=10000, null=True)),
                ('connection_agent_name', models.CharField(blank=True, max_length=10000, null=True)),
                ('connection_agent_description', models.CharField(blank=True, max_length=10000, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Orchestration Connection',
                'verbose_name_plural': 'Orchestration Connections',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['created_at'], name='messaging_o_created_18cbdd_idx')],
            },
        ),
        migrations.AddField(
            model_name='multimodalorchestrationchat',
            name='connection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='multimodal_orchestration_chats', to='messaging.orchestrationconnection'),
        ),
        migrations.CreateModel(
            name='ElectronCopilotConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('connection_type_selection', models.CharField(choices=[('assistant', 'Assistant'), ('leanmod', 'Leanmod'), ('orchestration', 'Orchestration')], default='assistant', max_length=255)),
                ('last_toggled_is_active_at', models.DateTimeField(auto_now_add=True)),
                ('assistant_connection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assistant_connection', to='messaging.assistantconnection')),
                ('leanmod_connection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leanmod_connection', to='messaging.leanmodconnection')),
                ('assistant_chat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assistant_chat', to='messaging.multimodalassistantchat')),
                ('leanmod_chat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leanmod_chat', to='messaging.multimodalleanmodchat')),
                ('orchestration_chat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orchestration_chat', to='messaging.multimodalorchestrationchat')),
                ('orchestration_connection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orchestration_connection', to='messaging.orchestrationconnection')),
            ],
            options={
                'verbose_name': 'Electron Copilot Configuration',
                'verbose_name_plural': 'Electron Copilot Configurations',
                'ordering': ['-last_toggled_is_active_at'],
            },
        ),
        migrations.AddIndex(
            model_name='multimodalassistantchat',
            index=models.Index(fields=['created_at'], name='messaging_m_created_89c50f_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalassistantchatmessage',
            index=models.Index(fields=['sent_at'], name='messaging_m_sent_at_4ec63a_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalleanmodchat',
            index=models.Index(fields=['created_at'], name='messaging_m_created_6e6614_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalleanmodchatmessage',
            index=models.Index(fields=['sent_at'], name='messaging_m_sent_at_291f73_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalorchestrationchatmessage',
            index=models.Index(fields=['sent_at'], name='messaging_m_sent_at_499665_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalorchestrationchat',
            index=models.Index(fields=['created_at'], name='messaging_m_created_724035_idx'),
        ),
        migrations.AddIndex(
            model_name='electroncopilotconfiguration',
            index=models.Index(fields=['last_toggled_is_active_at'], name='messaging_e_last_to_50f3c4_idx'),
        ),
    ]
