# Generated by Django 5.0.6 on 2024-10-30 04:07

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MetaTempoConnectionConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_tracking_active', models.BooleanField(default=True)),
                ('member_log_intervals', models.CharField(choices=[('times_12_per_hour', '12 Times Per Hour'), ('times_6_per_hour', '6 Times Per Hour'), ('times_4_per_hour', '4 Times Per Hour'), ('times_3_per_hour', '3 Times Per Hour'), ('times_2_per_hour', '2 Times Per Hour'), ('hourly', 'Hourly'), ('every_2_hours', 'Every 2 Hours'), ('every_4_hours', 'Every 4 Hours')], default='times_6_per_hour', max_length=1000)),
                ('tracked_weekdays', models.JSONField(blank=True, null=True)),
                ('tracking_start_time', models.TimeField(blank=True, null=True)),
                ('tracking_end_time', models.TimeField(blank=True, null=True)),
                ('connection_api_key', models.CharField(blank=True, max_length=10000, null=True)),
                ('user_auth_key', models.CharField(blank=True, max_length=10000, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'MetaTempo Connection Configuration',
                'verbose_name_plural': 'MetaTempo Connection Configurations',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['is_tracking_active'], name='metatempo_m_is_trac_71c996_idx'), models.Index(fields=['member_log_intervals'], name='metatempo_m_member__a17653_idx'), models.Index(fields=['connection_api_key'], name='metatempo_m_connect_72d97f_idx'), models.Index(fields=['user_auth_key'], name='metatempo_m_user_au_35676f_idx'), models.Index(fields=['created_at'], name='metatempo_m_created_fdd045_idx'), models.Index(fields=['updated_at'], name='metatempo_m_updated_301a97_idx')],
            },
        ),
        migrations.CreateModel(
            name='MetaTempoLogRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier_uuid', models.UUIDField(default=uuid.uuid4)),
                ('screenshot_image_png', models.ImageField(blank=True, null=True, upload_to='metatempo/logs/%Y/%m/%d/')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'MetaTempo Log Record',
                'verbose_name_plural': 'MetaTempo Log Records',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['identifier_uuid'], name='metatempo_m_identif_1b333a_idx'), models.Index(fields=['timestamp'], name='metatempo_m_timesta_04f215_idx')],
            },
        ),
    ]
