# Generated by Django 5.0.6 on 2024-10-30 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metatempo', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='metatempoconnectionconfiguration',
            new_name='metatempo_b_is_trac_636215_idx',
            old_name='metatempo_m_is_trac_71c996_idx',
        ),
        migrations.RenameIndex(
            model_name='metatempoconnectionconfiguration',
            new_name='metatempo_b_member__711802_idx',
            old_name='metatempo_m_member__a17653_idx',
        ),
        migrations.RenameIndex(
            model_name='metatempoconnectionconfiguration',
            new_name='metatempo_b_connect_747042_idx',
            old_name='metatempo_m_connect_72d97f_idx',
        ),
        migrations.RenameIndex(
            model_name='metatempoconnectionconfiguration',
            new_name='metatempo_b_user_au_5fd661_idx',
            old_name='metatempo_m_user_au_35676f_idx',
        ),
        migrations.RenameIndex(
            model_name='metatempoconnectionconfiguration',
            new_name='metatempo_b_created_d4f6f0_idx',
            old_name='metatempo_m_created_fdd045_idx',
        ),
        migrations.RenameIndex(
            model_name='metatempoconnectionconfiguration',
            new_name='metatempo_b_updated_8ff71e_idx',
            old_name='metatempo_m_updated_301a97_idx',
        ),
        migrations.AlterModelTable(
            name='metatempoconnectionconfiguration',
            table='metatempo_board_connection',
        ),
    ]
