# Generated by Django 5.0.6 on 2024-10-30 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metatempo', '0002_rename_metatempo_m_is_trac_71c996_idx_metatempo_b_is_trac_636215_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='metatempologrecord',
            name='is_sent_successfully',
            field=models.BooleanField(default=False),
        ),
    ]
