# Generated by Django 5.0.6 on 2024-10-30 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metatempo', '0003_metatempologrecord_is_sent_successfully'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='metatempologrecord',
            new_name='metatempo_l_identif_be50dc_idx',
            old_name='metatempo_m_identif_1b333a_idx',
        ),
        migrations.RenameIndex(
            model_name='metatempologrecord',
            new_name='metatempo_l_timesta_f1b364_idx',
            old_name='metatempo_m_timesta_04f215_idx',
        ),
        migrations.AlterModelTable(
            name='metatempologrecord',
            table='metatempo_log_record',
        ),
    ]
