# Generated by Django 5.0.6 on 2024-10-30 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metatempo', '0004_rename_metatempo_m_identif_1b333a_idx_metatempo_l_identif_be50dc_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metatempologrecord',
            name='screenshot_image_png',
            field=models.ImageField(blank=True, null=True, upload_to='metatempo/logs/'),
        ),
    ]
