# Generated by Django 5.0.6 on 2024-10-26 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AssistantConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('connection_endpoint', models.CharField(blank=True, max_length=10000, null=True)),
                ('connection_is_public', models.BooleanField(default=False)),
                ('connection_api_key', models.CharField(blank=True, max_length=10000, null=True)),
                ('connection_agent_name', models.CharField(blank=True, max_length=10000, null=True)),
                ('connection_agent_description', models.CharField(blank=True, max_length=10000, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Assistant Connection',
                'verbose_name_plural': 'Assistant Connections',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['created_at'], name='connections_created_f5ab78_idx')],
            },
        ),
        migrations.CreateModel(
            name='LeanmodConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('connection_endpoint', models.CharField(blank=True, max_length=10000, null=True)),
                ('connection_is_public', models.BooleanField(default=False)),
                ('connection_api_key', models.CharField(blank=True, max_length=10000, null=True)),
                ('connection_agent_name', models.CharField(blank=True, max_length=10000, null=True)),
                ('connection_agent_description', models.CharField(blank=True, max_length=10000, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'LeanMod Connection',
                'verbose_name_plural': 'LeanMod Connections',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['created_at'], name='connections_created_09f294_idx')],
            },
        ),
        migrations.CreateModel(
            name='OrchestrationConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('connection_endpoint', models.CharField(blank=True, max_length=10000, null=True)),
                ('connection_is_public', models.BooleanField(default=False)),
                ('connection_api_key', models.CharField(blank=True, max_length=10000, null=True)),
                ('connection_agent_name', models.CharField(blank=True, max_length=10000, null=True)),
                ('connection_agent_description', models.CharField(blank=True, max_length=10000, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Orchestration Connection',
                'verbose_name_plural': 'Orchestration Connections',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['created_at'], name='connections_created_02e235_idx')],
            },
        ),
    ]
