# Generated by Django 5.0.6 on 2024-10-26 00:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('connections', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assistantconnection',
            name='connection_agent_description',
        ),
        migrations.RemoveField(
            model_name='assistantconnection',
            name='connection_agent_name',
        ),
        migrations.RemoveField(
            model_name='leanmodconnection',
            name='connection_agent_description',
        ),
        migrations.RemoveField(
            model_name='leanmodconnection',
            name='connection_agent_name',
        ),
        migrations.RemoveField(
            model_name='orchestrationconnection',
            name='connection_agent_description',
        ),
        migrations.RemoveField(
            model_name='orchestrationconnection',
            name='connection_agent_name',
        ),
    ]
