# Generated by Django 5.0.6 on 2024-10-26 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connections', '0002_remove_assistantconnection_connection_agent_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assistantconnection',
            name='connection_endpoint',
            field=models.CharField(blank=True, max_length=10000, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='leanmodconnection',
            name='connection_endpoint',
            field=models.CharField(blank=True, max_length=10000, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='orchestrationconnection',
            name='connection_endpoint',
            field=models.CharField(blank=True, max_length=10000, null=True, unique=True),
        ),
    ]
