# Generated by Django 5.0.6 on 2024-11-25 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connections', '0003_alter_assistantconnection_connection_endpoint_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VoidForgerConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('connection_endpoint', models.CharField(blank=True, max_length=10000, null=True, unique=True)),
                ('connection_is_public', models.BooleanField(default=False)),
                ('connection_api_key', models.CharField(blank=True, max_length=10000, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'VoidForger Connection',
                'verbose_name_plural': 'VoidForger Connections',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['created_at'], name='connections_created_6c7370_idx')],
            },
        ),
    ]
