# Generated by Django 5.0.6 on 2024-10-26 00:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('connections', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MultimodalAssistantChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization_name', models.CharField(blank=True, max_length=10000, null=True)),
                ('agent_name', models.CharField(blank=True, max_length=10000, null=True)),
                ('chat_name', models.CharField(blank=True, max_length=10000, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('connection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='multimodal_assistant_chats', to='connections.assistantconnection')),
            ],
            options={
                'verbose_name': 'Multimodal Assistant Chat',
                'verbose_name_plural': 'Multimodal Assistant Chats',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MultimodalAssistantChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_role', models.CharField(choices=[('system', 'System'), ('assistant', 'Assistant'), ('user', 'User')], default='system', max_length=200)),
                ('message_text', models.TextField(blank=True, null=True)),
                ('message_file_uris', models.JSONField(blank=True, null=True)),
                ('message_image_uris', models.JSONField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assistant_messages', to='chats.multimodalassistantchat')),
            ],
            options={
                'verbose_name': 'Multimodal Assistant Chat Message',
                'verbose_name_plural': 'Multimodal Assistant Chat Messages',
                'ordering': ['-sent_at'],
            },
        ),
        migrations.CreateModel(
            name='MultimodalLeanmodChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization_name', models.CharField(blank=True, max_length=10000, null=True)),
                ('agent_name', models.CharField(blank=True, max_length=10000, null=True)),
                ('chat_name', models.CharField(blank=True, max_length=10000, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('connection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='multimodal_leanmod_chats', to='connections.leanmodconnection')),
            ],
            options={
                'verbose_name': 'Multimodal LeanMod Chat',
                'verbose_name_plural': 'Multimodal LeanMod Chats',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MultimodalLeanmodChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_role', models.CharField(choices=[('system', 'System'), ('assistant', 'Assistant'), ('user', 'User')], default='system', max_length=200)),
                ('message_text', models.TextField(blank=True, null=True)),
                ('message_file_uris', models.JSONField(blank=True, null=True)),
                ('message_image_uris', models.JSONField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leanmod_messages', to='chats.multimodalleanmodchat')),
            ],
            options={
                'verbose_name': 'Multimodal LeanMod Chat Message',
                'verbose_name_plural': 'Multimodal LeanMod Chat Messages',
                'ordering': ['-sent_at'],
            },
        ),
        migrations.CreateModel(
            name='MultimodalOrchestrationChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization_name', models.CharField(blank=True, max_length=10000, null=True)),
                ('agent_name', models.CharField(blank=True, max_length=10000, null=True)),
                ('chat_name', models.CharField(blank=True, max_length=10000, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('connection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='multimodal_orchestration_chats', to='connections.orchestrationconnection')),
            ],
            options={
                'verbose_name': 'Multimodal Orchestration Chat',
                'verbose_name_plural': 'Multimodal Orchestration Chats',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MultimodalOrchestrationChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_role', models.CharField(choices=[('system', 'System'), ('assistant', 'Assistant'), ('user', 'User')], default='system', max_length=200)),
                ('message_text', models.TextField(blank=True, null=True)),
                ('message_file_uris', models.JSONField(blank=True, null=True)),
                ('message_image_uris', models.JSONField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orchestration_messages', to='chats.multimodalorchestrationchat')),
            ],
            options={
                'verbose_name': 'Multimodal Orchestration Chat Message',
                'verbose_name_plural': 'Multimodal Orchestration Chat Messages',
                'ordering': ['-sent_at'],
            },
        ),
        migrations.AddIndex(
            model_name='multimodalassistantchat',
            index=models.Index(fields=['created_at'], name='chats_multi_created_3f0330_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalassistantchatmessage',
            index=models.Index(fields=['sent_at'], name='chats_multi_sent_at_c05ad4_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalleanmodchat',
            index=models.Index(fields=['created_at'], name='chats_multi_created_b11b65_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalleanmodchatmessage',
            index=models.Index(fields=['sent_at'], name='chats_multi_sent_at_c98141_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalorchestrationchat',
            index=models.Index(fields=['created_at'], name='chats_multi_created_1c0a0f_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalorchestrationchatmessage',
            index=models.Index(fields=['sent_at'], name='chats_multi_sent_at_8258ff_idx'),
        ),
    ]
