# Generated by Django 5.0.6 on 2024-10-26 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='multimodalassistantchat',
            name='agent_name',
        ),
        migrations.RemoveField(
            model_name='multimodalassistantchat',
            name='chat_name',
        ),
        migrations.RemoveField(
            model_name='multimodalassistantchat',
            name='organization_name',
        ),
        migrations.RemoveField(
            model_name='multimodalleanmodchat',
            name='agent_name',
        ),
        migrations.RemoveField(
            model_name='multimodalleanmodchat',
            name='chat_name',
        ),
        migrations.RemoveField(
            model_name='multimodalleanmodchat',
            name='organization_name',
        ),
        migrations.RemoveField(
            model_name='multimodalorchestrationchat',
            name='agent_name',
        ),
        migrations.RemoveField(
            model_name='multimodalorchestrationchat',
            name='chat_name',
        ),
        migrations.RemoveField(
            model_name='multimodalorchestrationchat',
            name='organization_name',
        ),
        migrations.AddField(
            model_name='multimodalassistantchat',
            name='uuid',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='multimodalleanmodchat',
            name='uuid',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='multimodalorchestrationchat',
            name='uuid',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
