# Generated by Django 5.0.6 on 2024-10-26 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0002_remove_multimodalassistantchat_agent_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='multimodalassistantchatmessage',
            name='message_file_uris',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='multimodalassistantchatmessage',
            name='message_image_uris',
            field=models.TextField(blank=True, null=True),
        ),
    ]
