# Generated by Django 5.0.6 on 2024-10-26 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0003_alter_multimodalassistantchatmessage_message_file_uris_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='multimodalleanmodchatmessage',
            name='message_file_uris',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='multimodalleanmodchatmessage',
            name='message_image_uris',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='multimodalorchestrationchatmessage',
            name='message_file_uris',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='multimodalorchestrationchatmessage',
            name='message_image_uris',
            field=models.TextField(blank=True, null=True),
        ),
    ]
