# Generated by Django 5.0.6 on 2024-11-25 03:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0004_alter_multimodalleanmodchatmessage_message_file_uris_and_more'),
        ('connections', '0004_voidforgerconnection'),
    ]

    operations = [
        migrations.CreateModel(
            name='MultimodalVoidForgerChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(blank=True, max_length=1000, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('connection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='multimodal_voidforger_chats', to='connections.voidforgerconnection')),
            ],
            options={
                'verbose_name': 'Multimodal VoidForger Chat',
                'verbose_name_plural': 'Multimodal VoidForger Chats',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MultimodalVoidForgerChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_role', models.CharField(choices=[('system', 'System'), ('assistant', 'Assistant'), ('user', 'User')], default='system', max_length=200)),
                ('message_text', models.TextField(blank=True, null=True)),
                ('message_file_uris', models.TextField(blank=True, null=True)),
                ('message_image_uris', models.TextField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assistant_messages', to='chats.multimodalvoidforgerchat')),
            ],
            options={
                'verbose_name': 'Multimodal VoidForger Chat Message',
                'verbose_name_plural': 'Multimodal VoidForger Chat Messages',
                'ordering': ['-sent_at'],
            },
        ),
        migrations.AddIndex(
            model_name='multimodalvoidforgerchat',
            index=models.Index(fields=['created_at'], name='chats_multi_created_6c5a0c_idx'),
        ),
        migrations.AddIndex(
            model_name='multimodalvoidforgerchatmessage',
            index=models.Index(fields=['sent_at'], name='chats_multi_sent_at_74e029_idx'),
        ),
    ]
