# Generated by Django 5.0.6 on 2024-11-25 03:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0005_multimodalvoidforgerchat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='multimodalvoidforgerchatmessage',
            name='chat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voidforger_messages', to='chats.multimodalvoidforgerchat'),
        ),
    ]
