# Generated by Django 5.0.6 on 2024-10-26 01:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chats', '0002_remove_multimodalassistantchat_agent_name_and_more'),
        ('connections', '0002_remove_assistantconnection_connection_agent_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CopilotModal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('active_connection_type', models.CharField(choices=[('assistant', 'Assistant'), ('leanmod', 'LeanMod'), ('orchestration', 'Orchestration')], default='assistant', max_length=255)),
                ('last_toggled_is_active_at', models.DateTimeField(auto_now=True)),
                ('selected_assistant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='connections.assistantconnection')),
                ('selected_assistant_chat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='chats.multimodalassistantchat')),
                ('selected_leanmod', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='connections.leanmodconnection')),
                ('selected_leanmod_chat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='chats.multimodalleanmodchat')),
                ('selected_orchestration', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='connections.orchestrationconnection')),
                ('selected_orchestration_chat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='chats.multimodalorchestrationchat')),
            ],
            options={
                'verbose_name': 'Copilot Modal',
                'verbose_name_plural': 'Copilot Modals',
            },
        ),
    ]
