# Generated by Django 5.0.6 on 2024-11-25 03:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0005_multimodalvoidforgerchat_and_more'),
        ('connections', '0004_voidforgerconnection'),
        ('copilot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='copilotmodal',
            name='selected_voidforger',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='connections.voidforgerconnection'),
        ),
        migrations.AddField(
            model_name='copilotmodal',
            name='selected_voidforger_chat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='chats.multimodalvoidforgerchat'),
        ),
        migrations.AlterField(
            model_name='copilotmodal',
            name='active_connection_type',
            field=models.CharField(choices=[('assistant', 'Assistant'), ('leanmod', 'LeanMod'), ('orchestration', 'Orchestration'), ('voidforger', 'VoidForger')], default='voidforger', max_length=255),
        ),
    ]
