# Generated by Django 5.0.6 on 2024-10-28 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MetaKanbanBoardConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('board_connection_api_key', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Meta Kanban Board Connection',
                'verbose_name_plural': 'Meta Kanban Board Connections',
                'db_table': 'meta_kanban_board_connection',
                'indexes': [models.Index(fields=['board_connection_api_key'], name='meta_kanban_board_c_4e6605_idx'), models.Index(fields=['created_at'], name='meta_kanban_created_32dfd1_idx')],
            },
        ),
    ]
